adding smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -30,17 +30,17 @@ commands:
           name: Revert migrations
           when: on_fail
           command: |
-            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            
             SUCCESS = $(curl --insecure https://kvdb.io/${KVDB_BUCKET_ID}/migration_<<parameters.workflow_id>>)
             if(( $SUCCESS==1 )); 
             then
             cd ~/project/backend
             npm install
             npm run migration:revert
-            #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
             fi
-            
+    # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+    #  Add revert code here. You can find this in the Getting Started section.
+          #    exit 1        
 jobs:
   build-frontend:
     docker:
@@ -185,11 +185,11 @@ jobs:
           template: basic_fail_1
           #message: "Job failed with error: {{ .FailureReason }} please help me"
         
-      # -  destroy-environment:
-      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-        # - revert-migrations:
-        #   workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-#       # Here's where you will add some code to rollback on failure      
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # Here's where you will add some code to rollback on failure      
 
   configure-infrastructure:
     docker:
@@ -218,11 +218,12 @@ jobs:
           template: basic_fail_1
           #message: "configure-infrastructure Job failed with error: {{ .FailureReason }} please help me"
         
-#       # Here's where you will add some code to rollback on failure  
-      # -  destroy-environment:
-      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}    
-      # - revert-migrations:
-        #   workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+       # Here's where you will add some code to rollback on failure  
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}    
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+
   run-migrations:
     docker:
       - image: circleci/node:13.8.0
@@ -251,10 +252,10 @@ jobs:
            #curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
            # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
      # Here's where you will add some code to rollback on failure      
-      # - destroy-environment:
-      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}    
-      #  - revert-migrations:
-        #   workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}    
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
           
   deploy-frontend:
     docker:
@@ -315,10 +316,10 @@ jobs:
             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
       # Here's where you will add some code to rollback on failure 
-      # - destroy-environment:
-      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}     
-      #- revert-migrations:
-        #   workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}        
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}     
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}        
 
   deploy-backend:
     docker:
@@ -366,10 +367,10 @@ jobs:
           event: fail
           template: basic_fail_1
       # Here's where you will add some code to rollback on failure  
-      #- destroy-environment:
-      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}    
-     # - revert-migrations:
-        #   workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}    
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
   smoke-test:
     docker:
       # Lightweight Docker image 
@@ -410,10 +411,10 @@ jobs:
               return 1
             fi
 #       # Here's where you will add some code to rollback on failure  
-      #- destroy-environment:
+      # - destroy-environment:
       #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}    
-     # - revert-migrations:
-        #   workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - revert-migrations:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
 #   cloudfront-update:
 #     docker:
